app:
  build: .
  dockerfile: .docker/pitchbattle/Dockerfile
  environment:
    DATABASE_HOSTNAME: db
    DATABASE_USERNAME: postgres
  links:
    - db
  expose:
    - '3000'
  command: puma

db:
  image: postgres:9.5.3
  volumes:
    - pitchbattle-postgres:/var/lib/postgresql/data

web:
  build: .
  dockerfile: .docker/web/Dockerfile
  links:
    - app
  ports:
    - '80:80'
